/*
 * Generated by the Mule project wizard. http://mule.mulesource.org
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */
package org.mule.transport.comm;


import org.mule.tck.FunctionalTestCase;

/**
 * TODO
 */
public class CommNamespaceHandlerTestCase extends FunctionalTestCase
{
    protected String getConfigResources()
    {
        //TODO You'll need to edit this file to configure the properties specific to your module elements
        return "comm-namespace-config.xml";
    }

    public void testCommConfig() throws Exception
    {
        //TODO Assert specific properties are configured correctly
        fail("Not implemented yet");

    }
}
