/*
 * Generated by the Mule project wizard. http://mule.mulesource.org
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */

package org.mule.transport.comm.i18n;

import org.mule.config.i18n.MessageFactory;
import org.mule.config.i18n.Message;
import org.mule.transport.comm.CommConnector;

import java.net.URI;

/**
 * Created by IntelliJ IDEA.
 * User: Christopher Cheng
 * Date: Mar 1, 2009
 * Time: 4:03:33 PM
 * To change this template use File | Settings | File Templates.
 */
public class CommMessages extends MessageFactory
{
    private static final CommMessages factory = new CommMessages();

    private static final String BUNDLE_PATH = getBundlePath(CommConnector.COMM);

    public static Message failedToBindToUri(URI uri)
    {
        return factory.createMessage(BUNDLE_PATH, 1, uri);
    }

    public static Message failedToCloseSocket()
    {
        return factory.createMessage(BUNDLE_PATH, 2);
    }

    public static Message failedToInitMessageReader()
    {
        return factory.createMessage(BUNDLE_PATH, 3);
    }

    public static Message invalidStreamingOutputType(Class c)
    {
        return factory.createMessage(BUNDLE_PATH, 4, c.getName());
    }
}
