/*
 * Generated by the Mule project wizard. http://mule.mulesource.org
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */

package org.mule.transport.comm.protocols;

/**
 * Created by IntelliJ IDEA.
 * User: kim
 * Date: 2009�~3��20��
 * Time: �U��05:11:53
 * To change this template use File | Settings | File Templates.
 */
public class ModbusProtocol {
}
