/*
 * Generated by the Mule project wizard. http://mule.mulesource.org
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */

package org.mule.transport.comm.config;

import org.mule.config.spring.parsers.delegate.BooleanAttributeSelectionDefinitionParser;
import org.mule.config.spring.parsers.generic.ChildDefinitionParser;

/**
 * Created by IntelliJ IDEA.
 * User: Christopher Sze-wai Cheng (christopher@skywidetech.com)
 * Date: Mar 1, 2009
 * Time: 4:02:01 PM
 * To change this template use File | Settings | File Templates.
 */
public class ByteOrMessageProtocolDefinitionParser extends BooleanAttributeSelectionDefinitionParser
{

    public static final String PROTOCOL = "commProtocol";

    public ByteOrMessageProtocolDefinitionParser(Class bytes, Class message)
    {
        super("payloadOnly", true,
                new ChildDefinitionParser(PROTOCOL, bytes),
                new ChildDefinitionParser(PROTOCOL, message));
    }

}
