/*
 * Generated by the Mule project wizard. http://mule.mulesource.org
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */
package org.mule.transport.comm;

import org.mule.transport.AbstractMessageDispatcherFactory;
import org.mule.transport.comm.CommMessageDispatcher;
import org.mule.api.transport.MessageDispatcher;
import org.mule.api.endpoint.OutboundEndpoint;
import org.mule.api.MuleException;

/**
 * Created by IntelliJ IDEA.
 * User: Christopher Cheng
 * Date: Mar 1, 2009
 * Time: 4:15:31 PM
 * To change this template use File | Settings | File Templates.
 */
public class CommMessageDispatcherFactory extends AbstractMessageDispatcherFactory
{

    public MessageDispatcher create(OutboundEndpoint endpoint) throws MuleException
    {
        try {
            return new CommMessageDispatcher(endpoint);
        }
        catch (Exception e) {
            e.printStackTrace(System.out);
            return null;
        }
    }

}
