/*
 * Generated by the Mule project wizard. http://mule.mulesource.org
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */
package org.mule.transport.comm;

import org.mule.transport.AbstractMessageRequesterFactory;
import org.mule.transport.comm.CommMessageRequester;
import org.mule.api.transport.MessageRequester;
import org.mule.api.endpoint.InboundEndpoint;
import org.mule.api.MuleException;

/**
 * Created by IntelliJ IDEA.
 * User: Christopher Cheng
 * Date: Mar 1, 2009
 * Time: 4:26:25 PM
 * To change this template use File | Settings | File Templates.
 */
public class CommMessageRequesterFactory extends AbstractMessageRequesterFactory
{

    public MessageRequester create(InboundEndpoint endpoint) throws MuleException
    {
        return new CommMessageRequester(endpoint);
    }

}