/*
 * Generated by the Mule project wizard. http://mule.mulesource.org
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */
package org.mule.transport.comm;

import javax.comm.CommPort;
import java.io.BufferedOutputStream;
import java.io.OutputStream;
import java.io.IOException;
import java.net.Socket;

/**
 * org.mule.transport.comm
 *
 * @author Christopher Cheng
 * @version $Id: Apr 23, 2009 12:48:25 PM
 */
public class ResponseOutputStream extends org.mule.ResponseOutputStream
{

    private Socket socket = null;

    private CommPort commPort = null;

    public ResponseOutputStream(OutputStream stream)
    {
        super(stream);
    }

    public ResponseOutputStream(Socket socket, OutputStream stream) throws IOException
    {
        super(stream);
        this.socket = socket;
    }

    public ResponseOutputStream(CommPort commPort, OutputStream stream) throws IOException
    {
        super(stream);
        this.commPort = commPort;
    }

    public Socket getSocket()
    {
        return socket;
    }

    public CommPort getCommPort() {
        return commPort;
    }

}