/*
 * Generated by the Mule project wizard. http://mule.mulesource.org
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */
package org.mule.transport.comm;

import javax.comm.CommPort;
import javax.comm.NoSuchPortException;
import javax.comm.PortInUseException;
import javax.comm.UnsupportedCommOperationException;
import java.io.IOException;
import java.net.URI;

/**
 * Created by IntelliJ IDEA.
 * User: Christopher Cheng
 * Date: Mar 1, 2009
 * Time: 2:45:17 PM
 * To change this template use File | Settings | File Templates.
 */
public interface SimpleServerPortFactory {

    /**
     * @param uri The address and port to connect to
     * @param backlog The backlog (or {@link org.mule.api.transport.Connector#INT_VALUE_NOT_SET})
     * @param reuse Whether to reuse addresses (null for default)
     * @return A new, bound server socket
     * @throws java.io.IOException
     */
    CommPort createCommPort(URI uri, int backlog, Boolean reuse) throws IOException;

//    CommPort createCommPort(InetAddress address, int port, int backlog, Boolean reuse) throws IOException;
    CommPort createCommPort(String port, int baudrate, int dataBits, int stopBits, int parity, int delay, Boolean backlog, Boolean reuse)
            throws NoSuchPortException, PortInUseException, UnsupportedCommOperationException;

    CommPort createCommPort(String portName, int backlog, Boolean reuse)
            throws NoSuchPortException, PortInUseException, UnsupportedCommOperationException;
}
